---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: guacamole
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: mariadb
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./guacamole
  prune: true
  wait: true
  timeout: 5m0s