---
apiVersion: v1
kind: Namespace
metadata:
  name: bitnami
  labels:
    name: bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: bitnami
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: bitnami
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeapps
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: bitnami
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapps-operator
  namespace: bitnami
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeapps-operator
  namespace: bitnami
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubeapps-operator
    namespace: bitnami
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeapps-operator-token
  namespace: bitnami
  annotations:
    kubernetes.io/service-account.name: kubeapps-operator
type: kubernetes.io/service-account-token