---
apiVersion: v1
kind: Namespace
metadata:
  name: bitnami
  labels:
    name: bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: bitnami
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: bitnami
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeapps
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: bitnami