apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
  namespace: default
spec:
  replicas: 3
  maxScale:
    enabled: true
  galera:
    enabled: true
  storage:
    size: 2Gi
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: data-test
  namespace: default
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  mariaDbRef:
    name: mariadb-min
  characterSet: utf8
  collate: utf8_general_ci
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
  namespace: default
spec:
  mariaDbRef:
    name: mariadb-min
  privileges:
    - "ALL"
  database: "*"
  table: "*"
  username: user
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: default
data:
  password: dXNlcg==
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: user
  namespace: default
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb-min
  passwordSecretKeyRef:
    name: user
    key: password
  # This field is immutable and defaults to 10
  maxUserConnections: 200
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s